---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# AMKAT Simulation Study

<!-- badges: start -->
<!-- badges: end -->

This is the R project used to house the source code, simulated data and full analysis of results for the simulation study found in:

Brian Neal and Tao He. "An Adaptive Multivariate Kernel-Based Test for Association with Multiple Quantitative Traits in High-Dimensional Data." Genetic Epidemiology (Not yet submitted).


## State of Progress

This R project is currently in progress and is not yet fully complete: 

* Source code and simulated results are largely in a completed state. 
* Markdown documents for analysis of results are mostly in skeletal form with analysis and commentary to be added.


## Simulation Design

A complete description of the simulation study design can be found in our paper. Included here are documents related to the implementation of our study design in R.

* [Initialization Script for Simulation Scenarios](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/setup.html)
* [Correlation Heatmaps for Simulated SNP Set and its Signal Subsets](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/SNPset_corr_heatmaps.html)



## Analysis of Results

* Size
* [Proposed P-value Estimator](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/pval_estimator.html)
* [Power](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/power.html)
* [Kernel Selection (Across Data Replicates)](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/kernel_selection.html)
* [PhiMr Filter for Feature Selection (Across Data Replicates)](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/feature_selection.html)
* [Runtime Benchmarking](https://github.com/brianpatrickneal/AMKAT_simstudy/blob/main/markdown/runtime_benchmarking.html)