\documentclass[a4paper,oneside,10pt]{article}
\usepackage{a4wide} %%Smaller margins = more text per page.
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
<<setup, include=F>>=
options(knitr.table.format = 'latex')
library(kableExtra)
@

<<size_normal, echo=F>>=
size_or_power <- 'size'
alpha <- 0.05
num_permutations <- 1000
num_replicates <- 5000
x_type <- 'snp'
error_distribution <- 'normal'
table_filename_stem <- paste0(
          size_or_power, '_a', alpha * 1000, '_b', num_permutations,
          '_m', num_replicates, '_', x_type, '_', error_distribution)
load(paste0(table_filename_stem, '.Rdata'))
kbl(compiled_data, booktabs = T, escape = F,
    caption = caption) %>%
  # kable_styling(full_width = T) %>%
  # kable_styling(latex_options = 'scale_down') %>%
  kable_styling() %>%
  add_header_above(headrow) %>%
  pack_rows(index = rowgroupindex)
@

<<size_cauchy, echo=F>>=
size_or_power <- 'size'
alpha <- 0.05
num_permutations <- 1000
num_replicates <- 5000
x_type <- 'snp'
error_distribution <- 'cauchy'
table_filename_stem <- paste0(
          size_or_power, '_a', alpha * 1000, '_b', num_permutations,
          '_m', num_replicates, '_', x_type, '_', error_distribution)
load(paste0(table_filename_stem, '.Rdata'))
kbl(compiled_data, booktabs = T, escape = F,
    caption = caption) %>%
  # kable_styling(full_width = T) %>%
  # kable_styling(latex_options = 'scale_down') %>%
  kable_styling() %>%
  add_header_above(headrow) %>%
  pack_rows(index = rowgroupindex)
@




\end{document}
